# Generated by Django 6.0.5 on 2026-06-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='nom',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='cognoms',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='caption',
            new_name='tag',
        ),
    ]
